#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push checks..."

# Run build
echo "Running build..."
npm run build || exit 1

# Run tests
echo "Running tests..."
npm run test || exit 1

echo "Pre-push checks passed!"
